"use client";
import { BarChart, Bar, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const continentData = [
  {year:"1930",Europe:18,SouthAmerica:13,Africa:0,Asia:0},{year:"1950",Europe:42,SouthAmerica:25,Africa:0,Asia:1},
  {year:"1970",Europe:54,SouthAmerica:34,Africa:3,Asia:4},{year:"1990",Europe:66,SouthAmerica:42,Africa:12,Asia:8},
  {year:"2010",Europe:76,SouthAmerica:47,Africa:20,Asia:16},{year:"2022",Europe:82,SouthAmerica:50,Africa:26,Asia:22}
];
const gapData = [{year:"1930s",giants:2.8,others:1.7},{year:"1950s",giants:2.5,others:1.45},{year:"1970s",giants:2.1,others:1.05},{year:"1990s",giants:1.65,others:.65},{year:"2010s",giants:1.3,others:.38},{year:"2020s",giants:1.05,others:.27}];
const upsetData = [{name:"Morocco–Belgium",gap:46},{name:"Japan–Germany",gap:45},{name:"Korea–Germany",gap:41},{name:"Croatia–Argentina",gap:34},{name:"Costa Rica–Greece",gap:31}];
const semisData = [{year:"1930",Europe:5,SouthAmerica:4,Africa:0,Other:0},{year:"1950",Europe:5,SouthAmerica:4,Africa:0,Other:0},{year:"1970",Europe:5,SouthAmerica:3,Africa:0,Other:0},{year:"1990",Europe:5,SouthAmerica:2,Africa:0,Other:0},{year:"2010",Europe:4,SouthAmerica:2,Africa:1,Other:0},{year:"2022",Europe:4,SouthAmerica:1,Africa:1,Other:1}];

const card = "panel min-h-[300px] p-4";
const tooltip = { backgroundColor: "#07131c", border: "1px solid rgba(148,163,184,.2)", borderRadius: 8 };
export function ContinentChart(){return <div className={card}><h3 className="text-xs font-bold uppercase tracking-wider">Knockout appearances by continent</h3><p className="mt-1 text-xs text-slate-400">Cumulative appearances in knockout stages</p><div className="mt-4 h-[230px]"><ResponsiveContainer><LineChart data={continentData}><CartesianGrid stroke="#18303f"/><XAxis dataKey="year"/><YAxis/><Tooltip contentStyle={tooltip}/><Legend/><Line dataKey="Europe" stroke="#6ed365" strokeWidth={2}/><Line dataKey="SouthAmerica" stroke="#e8bd43" strokeWidth={2}/><Line dataKey="Africa" stroke="#e3625d" strokeWidth={2}/><Line dataKey="Asia" stroke="#6787ff" strokeWidth={2}/></LineChart></ResponsiveContainer></div></div>}
export function GapChart(){return <div className={card}><h3 className="text-xs font-bold uppercase tracking-wider">Average goal difference</h3><p className="mt-1 text-xs text-slate-400">Top five traditional powers versus other teams</p><div className="mt-4 h-[230px]"><ResponsiveContainer><LineChart data={gapData}><CartesianGrid stroke="#18303f"/><XAxis dataKey="year"/><YAxis/><Tooltip contentStyle={tooltip}/><Legend/><Line dataKey="giants" name="Top 5 teams" stroke="#67cf63" strokeWidth={2}/><Line dataKey="others" name="Other teams" stroke="#efbc42" strokeWidth={2}/></LineChart></ResponsiveContainer></div></div>}
export function UpsetChart(){return <div className={card}><h3 className="text-xs font-bold uppercase tracking-wider">Biggest upsets</h3><p className="mt-1 text-xs text-slate-400">Selected matches by ranking gap</p><div className="mt-4 h-[230px]"><ResponsiveContainer><BarChart data={upsetData} layout="vertical"><CartesianGrid stroke="#18303f"/><XAxis type="number"/><YAxis dataKey="name" type="category" width={112}/><Tooltip contentStyle={tooltip}/><Bar dataKey="gap" fill="#73b84b" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div></div>}
export function SemisChart(){return <div className={card}><h3 className="text-xs font-bold uppercase tracking-wider">Teams reaching semi-finals</h3><p className="mt-1 text-xs text-slate-400">By confederation over time</p><div className="mt-4 h-[230px]"><ResponsiveContainer><BarChart data={semisData}><CartesianGrid stroke="#18303f"/><XAxis dataKey="year"/><YAxis/><Tooltip contentStyle={tooltip}/><Legend/><Bar dataKey="Europe" stackId="a" fill="#65bd65"/><Bar dataKey="SouthAmerica" stackId="a" fill="#e8bd43"/><Bar dataKey="Africa" stackId="a" fill="#e35d58"/><Bar dataKey="Other" stackId="a" fill="#8a70df"/></BarChart></ResponsiveContainer></div></div>}
