# Generated by Django 5.2.17 on 2026-08-08 21:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('queries', models.JSONField()),
                ('results', models.JSONField()),
                ('evidence', models.TextField()),
                ('plan', models.TextField()),
                ('original_story', models.TextField()),
                ('current_story', models.TextField()),
                ('charts', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('instruction', models.TextField()),
                ('story', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='stories.storygeneration')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('story_generation', 'number'), name='unique_story_revision_number')],
            },
        ),
    ]
