export const humanStory = {
  version: "human-story-v1",
  paragraphs: [
    "It's 1966 and the founders of football, England have finally hosted a world cup on home soil. A period of warm sunshine preceded the lunchtime scenes across West London on the 11th of July with spectators gathering around the city to support their team in the historic Old Wembley. Brian Moore and Alan Clarke's commentary on BBC radio. Kenneth Wolstenholme's iconic commentary for the World Cup. A world cup consisting of 16 teams with Africa and Oceania not presented by a single nation. 10 of the 16 teams were European with the three South American powerhouses representing their continent alongside then bronze medalists Chile. Mexico and North Korea completed the set. Many consider the African Boycott of this edition this to be the start of the revolution within the FIFA members. 60 years later in 2026, Morocco, Norway and Japan entered the FIFA World Cup as top 10 favorites. But how did the World Cup shift from being the centre court for Diego Maradona, Pele and Johan Cruyff to showcase their ability with everyone else filling up the numbers to underdogs like Cape Verde's Vozinha stealing the show. ",
    "They have Messi, We have Mo Salah:",
    "The rise globalization in the late 1990s and Early 2000s broke a horizon in the football industry that changed the scale of the game. The Bosman rulings and the easing of foreign player restrictions allowed the best players from all over the world to play in the most prestigious leagues in the world. Hidetoshi Nakata, George Weah and Mark Viduka. Cult heroes of early modern day football who broke through to the biggest leagues from the less fancy nations were a small part of the revolution which eventually led to similar footballers like Lewandowski and Heung-min Son being uncontestably world class players. This calibre of players would prove to elevate their teams to new heights as previously mentioned by members of the Egyptian squad in the 2026 world cup who hailed their Captain Mo Salah as the best player in the world. The fear of the “German Machines” and the “Superior Brazilians” is constantly ceasing to exist with many of the smaller nations have their own superstars.",
    "From Casablanca to Utrecht:", 
    "The rise of migration during the post-colonial world and cold war era and its subsequent events has created an unprecedented pool of 2nd generation dual nationals. Go back 56 years ago in 1970, Morocco have qualified to their first ever world cup, 2nd African team to qualify since Egypt qualified back in 1934. A very respectable performance from the Atlas Lions but they fell short in the groups stage with the local newspapers then citing lack of exposure to foreign forms of soccer. In 2022 Morocco with a mix of local players from Raja and Wydad Casablanca and an array of Moroccan diaspora from Belgium, Netherlands and France managed to lead Morocco to a historic 4th place finish.  Young footballers having access to state of the art facilities and comprehensive training programs from a very young age mixed with their own style of football has produced several programs like Morocco, Senegal and Curacao.",
    "Breaking the Stereotypes:", 
    "We have Brazil at home. It is 1982 in Sunny Gijon, West Germany Manager Jupp Derwall joked that he would catch the 'first train back to Munich' if they lost against debutants Algeria, and stated he did not show his squad footage of Algeria because his players 'would have laughed about me'. 24 hours later Lakhdar Baloumi, unmarked diverted a cross to make it 2-1 for Algeria. For years, the footballing world has been guilty of stereotyping certain nations. Africans were always dubbed as athletic players who lacked technical knowledge, their Asian counterparts would beat everyone in a technical battle but their physicality lets them down. The Americans? What do they know about football, they call it soccer! Generation after generation parroted what might previously had been the right consensus, however the landscape of football has changed. Japan can match Netherlands in a physical battle, the USA can outshine Portugal and Senegal can play France off the park. Lionel Scaloni's historical Argentina side were matched and sometimes outmatched by Saudi Arabia, Cape Verde and Egypt. Croatia, a country that as late as 1995 were fighting for independence has managed to solidify itself as a World Cup marquees with 3 medals since their debut in 1998.",
    "Ball don't lie and neither do stats:", 
    "If we look at the data between the first 12 word cup editions (till 1982) and the subsequent last 11 editions. We can trace the narrowing disparity between the traditional powerhouses and the emerging nations, while you could rightfully contradict the statement by raising the counterpoint of more “emerging nations” participating in the world so their results against each other improves the overall stats between Team “Powerhouse” and Team “Underdogs”, we have seen several notable results and performances in the last 40 years that suggest an overall improvement in the average performance of the rest of the world. Teams from Asia, Africa and Eastern Europe have all been part of the semi finals in the recent editions of the tournament. Several countries have recorded their own David vs Goliath moments in the recent tournaments most notably Saudi Arabia vs Argentina, Costa Rica dismantling the group of death in 2014 and South Korea powering their way through Portugal, Italy and Spain on home soil in 2002. Italy, Previously world cup mainstays have failed to qualify to the last 3 editions of the world cup losing out to the likes of North Macedonia and Bosnia.",
    "Nothing ever happens, Euro Team vs Argentina!", 
    "While the excitement of an underdog captivates us with the best storylines, underdogs have ultimately fell short of winning the tournament. The American dream of post 1994 never materialized, Japan's blue lock references haven't seen them progress past the first knockout round and Africa still hasn't produced their own World Cup winner. In the famous worlds of Tunisian Commentator Issam Elchaouli “ Will I ever live to the day I see an African or Arab world cup winner?” The question looms in the heads of not just him, but every football supporter who wasn't fortunate enough to be born in a country that produces Lionel Messi and Diego Maradona or a country that has Clairefontaine. But the future is bright, there are no pushovers in the world cup stage right now, every country on its day can navigate their way to a victory against the elites of Football.",
  ],
};
